# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
  maxParallel: 1

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: python -m pip install --upgrade pipenv
    displayName: 'install setup tools'

  - script: pipenv install
    displayName: 'install dependencies'

  - script: pipenv run python setup.py sdist
    displayName: 'build package'

  - script: pipenv run flake8 .
    displayName: 'Run linter'

  - script: pipenv run python -m unittest tests/*_test.py
    displayName: 'Test with pytest'

#  - task: PublishTestResults@2
#    condition: succeededOrFailed()
#    inputs:
#      testResultsFiles: '**/test-*.xml'
#      testRunTitle: 'Publish test results for Python $(python.version)'
#
#  - task: PublishCodeCoverageResults@1
#    inputs:
#      codeCoverageTool: Cobertura
#      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
#      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
## - script: |
#     twine upload -r pypi -p $(password) dist/orca-version.tar.gz
#   displayName: publish package
